### ISSUE TITLE
Installation fails on macOS 12.4

### ISSUE THREAD

**Issue by mthielemann** [yep/virtualOS#2]
If I run the app on macOS 12.4, I get the following error after the restore image has been downloaded: 

```
Error: Install failed: Error Domain=VZErrorDomain Code=1 "Installation failed." UserInfo={NSLocalizedFailure=Internal Virtualization
error., NSLocalizedFailureReason=Installation failed., NSUnderlyingError=0x6000016fc060 {Error Domain=VZErrorDomain Code=1
"(null)"}}
```

**Comment by MattMacs** [comment]
Hi, running virtualOS here on macOS 12.4 like a charm, so more information would be great.

MBA 13" 2020 M1 16GB 1 TB 👍🏼

**Comment by mthielemann** [comment]
Tried it on a MBP 14" 2021 M1 Max with 64 GB for days now and today for whatever reason it worked for the first time. This is a bit weird because nothing really changed. 🤷🏻‍♂️

**Comment by zanza89** [comment]
I tried to install it for the third time now... still getting the same Error on MBP MAX 2021 16" 64GB model. However the Start Button and the configuration window appear anyway but when I click on it nothing happens.

`Error: Install failed: Error Domain=VZErrorDomain Code=1 "Installation failed." UserInfo={NSLocalizedFailure=Internal Virtualization
error., NSLocalizedFailureReason=Installation failed., NSUnderlyingError=0x6000033ff5d0 {Error Domain=VZErrorDomain Code=1
"(null)"}}`

**Comment by p4dt1** [comment]
I got my new MBP Max 2021 16" 64 GB and get the same like @zanza89 

Error: Install failed: Error Domain=VZErrorDomain Code=1 "Installation failed." Userinfo=(NSLocalizedFailure=Internal Virtualization error., NSLocalizedFailureRea:
(Error Domain=VZErrorDomain Code=1 "(null)")) 

Also the Start Button and the configuration window appear anyway but when I click on it nothing happens.

**Comment by yep** [comment]
For testing, I just installed a macOS 12.4 virtual machine on a macOS 12.4 host and did not see the above error.

The error message originates [here](https://github.com/yep/virtualOS/blob/v1.0/virtualOS/Model/VirtualMac.swift#L287). It happens when [VZMacOSInstaller](https://developer.apple.com/documentation/virtualization/vzmacosinstaller) runs the [install()](https://developer.apple.com/documentation/virtualization/vzmacosinstaller/3816619-install) method.

Everything that happens after starting the virtual machine install is kind of a black box and probably only Apple knows what happens during install exactly. The only visible event is "completion" of the install, which returns the mentioned error. I propose you create an account at the Apple [developer forum](https://developers.apple.com/forums/) and ask there. Chances are that an Apple Engineer can provide additional information.

As users reported the install to complete eventually after trying a number of times, you could try to install again by deleting the current virtual machine by selecting "Delete Virtual Machine" in the file menu.

**Comment by yep** [comment]
Hello everybody,

Could you please try if install succeeds using UTM?
https://github.com/utmapp/UTM

Another user [reported](https://github.com/yep/virtualOS/issues/10#issuecomment-1159407150) a similar (or the same) error is reproducible using UTM.

I have temporarily seen a similar error on my machine as well. In my tests, the install error only occurred for one specific restore image (.ipsw), all other restore images were working fine. Additionally, the error disappeared "after some time". This was reported by mthielemann [above](https://github.com/yep/virtualOS/issues/2#issuecomment-1131948753) as well.

Unfortunately, I only have very generic suggestions you could try:
- Power down the machine (not reboot), delete both the VM file and restore image, then try again. Use the file menu to delete the files: `File -> Delete Restore Image` and `File -> Delete Virtual Machine`. You can also delete the data manually: In Finder, in the "Go" menu, select "Go to Folder..." (Or press command-shift-g). Go to this folder: `~/Library/Containers/com.github.yep.ios.virtualOS/Data`. Delete both `virtualOS.bundle` and `RestoreImage.ipsw` and start over.
- Is there enough free disk space? The restore image is about 12 GB and the default disk image size is 64 GB. In the beta of version 1.1, the disk size can be configured in the settings. Get the beta from https://testflight.apple.com/join/vWKNYgmM
- Is there enough free RAM? You could try to close all other apps during install.

- In [beta 1.1](https://testflight.apple.com/join/vWKNYgmM), it is possible to select a custom restore image. You could try to download and install a different macOS version from https://ipsw.me/product/Mac

If the start button and the configuration window appear but the VM does not start, this is possibly due to an incomplete or failed install. In this case, please delete the virtual machine bundle as described above.
Improved error handling for incomplete installs will (hopefully) be added in the future.
