### ISSUE TITLE
"@" key not working

### ISSUE THREAD

**Issue by alanakra** [yep/virtualOS#32]
I can't type the @ key using my machine's built-in keyboard. Has anyone else ever encountered this problem and if so, were they able to solve it?

Host Machine: MacBook Pro M1 2020
Host OS: Sonoma 14.0
virtualOS 1.3.2 (Build 13)
VM OS version: Ventura 13.5.2

**Comment by yep** [comment]
To narrow down possible sources of this error, could you please provide additional information:
 - What is your physical keyboard layout/language?
 - What is your host's keyboard language? -> Settings -> Keyboard -> Text Input
 - What is your host's system language? -> Settings -> General -> Language & Region -> Preferred Languages -> Primary

Another user reported in #7 that the @ sign is on option-q instead of option-l

**Comment by alanakra** [comment]
- My Keyboard is French (AZERTY)
- Host's keyboard language: French
- Guest's keyboard language: French
- Host's and guest's system language: French for both

**Comment by WilsonApexive** [comment]
Works fine for me on both external keyboard and built-in keyboard with US English.

**Comment by alanakra** [comment]
I figured it out!
I simply opened the visual keyboard to see the layout of the keys and was surprised to see that the layout of the spots on my VM is not the same as that on the host.
Here's the visual keyboard of my host machine and a physical AZERTY keyboard.

<img width="604" alt="Capture d’écran 2023-12-03 à 00 24 07" src="https://github.com/yep/virtualOS/assets/50582251/54d81233-8b46-408d-8355-ca12d85e7110">
<img width="604" alt="azerty" src="https://github.com/yep/virtualOS/assets/50582251/704601b4-6e7f-4397-a78f-c0fe028621b5">


On the virtual machine, the "@" key doesn't appear directly, whereas the keyboard has the AZERTY configuration. To type the "@" key, hold down Option (⌥) and select "@", which is located next to the "Enter" key (see recording below).

https://github.com/yep/virtualOS/assets/50582251/bda2a979-ff96-42fd-805a-b86e953a1315
